DEF MARINE_RIBBON     EQU $00
DEF LAND_RIBBON       EQU $01
DEF SKY_RIBBON        EQU $02
DEF COUNTRY_RIBBON    EQU $03
DEF NATIONAL_RIBBON   EQU $04
DEF EARTH_RIBBON      EQU $05
DEF WORLD_RIBBON      EQU $06
