DEF AQUA_LEADER  EQU $00 ; *
DEF TEAM_AQUA_M  EQU $01 ; TEAM AQUA*
DEF TEAM_AQUA_F  EQU $02 ; TEAM AQUA*
; no AQUA ADMIN
DEF AROMA_LADY   EQU $03
DEF RUIN_MANIAC  EQU $04
DEF INTERVIEWER  EQU $05 ; *
DEF TUBER_F      EQU $06 ; TUBER
DEF TUBER_M      EQU $07 ; TUBER
DEF COOLTRAINER_M EQU $08 ; COOLTRAINER♂
DEF COOLTRAINER_F EQU $09 ; COOLTRAINER♀
DEF HEX_MANIAC   EQU $0A
DEF LADY         EQU $0B
DEF BEAUTY       EQU $0C
DEF RICH_BOY     EQU $0D
DEF POKEMANIAC   EQU $0E ; POKéMANIAC
DEF SWIMMER_M    EQU $0F ; SWIMMER♂
DEF TC_BLACK_BELT EQU $10 ; item name
DEF GUITARIST    EQU $11
DEF KINDLER      EQU $12
DEF CAMPER       EQU $13
DEF BUG_MANIAC   EQU $14
DEF PSYCHIC_M    EQU $15 ; PSYCHIC
DEF PSYCHIC_F    EQU $16 ; PSYCHIC
DEF GENTLEMAN    EQU $17
DEF ELITE_FOUR_SIDNEY EQU $18 ; ELITE FOUR*
DEF ELITE_FOUR_PHOEBE EQU $19 ; ELITE FOUR*
DEF LEADER_ROXANNE   EQU $1A ; LEADER*
DEF LEADER_BRAWLY    EQU $1B ; LEADER*
DEF LEADER_TATE_LIZA EQU $1C ; LEADER*
DEF SCHOOL_KID_M EQU $1D ; SCHOOL KID
DEF SCHOOL_KID_F EQU $1E ; SCHOOL KID
DEF SR_AND_JR    EQU $1F ; SR. AND JR.*
; no WINSTRATE
DEF POKEFAN_M    EQU $20 ; POKéFAN
DEF POKEFAN_F    EQU $21 ; POKéFAN
DEF EXPERT_M     EQU $22 ; EXPERT
DEF EXPERT_F     EQU $23 ; EXPERT
DEF YOUNGSTER    EQU $24
DEF CHAMPION     EQU $25 ; *
DEF FISHERMAN    EQU $26
DEF TRIATHLETE_M_BIKE EQU $27 ; TRIATHLETE
DEF TRIATHLETE_F_BIKE EQU $28 ; TRIATHLETE
DEF TRIATHLETE_M_RUN  EQU $29 ; TRIATHLETE
DEF TRIATHLETE_F_RUN  EQU $2A ; TRIATHLETE
DEF TRIATHLETE_M_SWIM EQU $2B ; TRIATHLETE
DEF TRIATHLETE_F_SWIM EQU $2C ; TRIATHLETE
DEF DRAGON_TAMER EQU $2D
DEF BIRD_KEEPER  EQU $2E
DEF NINJA_BOY    EQU $2F
DEF BATTLE_GIRL  EQU $30
DEF PARASOL_LADY EQU $31
DEF SWIMMER_F    EQU $32 ; SWIMMER♀
DEF PICNICKER    EQU $33
DEF TWINS        EQU $34 ; *
DEF SAILOR       EQU $35
DEF BOARDER_1    EQU $36 ; *
DEF BOARDER_2    EQU $37 ; *
DEF COLLECTOR    EQU $38
DEF PKMN_TRAINER_WALLY     EQU $39 ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_BRENDAN_1 EQU $3A ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_BRENDAN_2 EQU $3B ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_BRENDAN_3 EQU $3C ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_MAY_1     EQU $3D ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_MAY_2     EQU $3E ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_MAY_3     EQU $3F ; \{PKMN} TRAINER*
DEF PKMN_BREEDER_M EQU $40 ; \{PKMN} BREEDER
DEF PKMN_BREEDER_F EQU $41 ; \{PKMN} BREEDER
DEF PKMN_RANGER_M  EQU $42 ; \{PKMN} RANGER
DEF PKMN_RANGER_F  EQU $43 ; \{PKMN} RANGER
DEF MAGMA_LEADER EQU $44 ; *
DEF TEAM_MAGMA_M EQU $45 ; *
DEF TEAM_MAGMA_F EQU $46 ; *
; no MAGMA ADMIN
DEF LASS         EQU $47
DEF BUG_CATCHER  EQU $48
DEF HIKER        EQU $49
DEF YOUNG_COUPLE EQU $4A ; *
DEF OLD_COUPLE   EQU $4B ; *
DEF SIS_AND_BRO  EQU $4C ; *
; $4D: BLACK BELT with a Lass sprite
; $4E: PKMN TRAINER with a Youngster sprite
; $4F: GUITARIST with a Youngster sprite
; $8F: GENTLEMAN with a PKMN Breeder sprite
; $FB: TWINS with May’s sprite
; $FC: PKMN TRAINER with a Pokéfan (♂) sprite
; $FD: SAILOR with May’s sprite
; $FE: PKMN TRAINER with a Sis and Bro sprite
; $FF: BOARDER with May’s sprite
