MACRO eggmons
    dw BULBASAUR
    dw CHARMANDER
    dw SQUIRTLE
    dw PIDGEY
    dw RATTATA
    dw SPEAROW
    dw EKANS
    dw SANDSHREW
    dw NIDORAN_F
    dw NIDORAN_M
    dw VULPIX
    dw ZUBAT
    dw ODDISH
    dw PARAS
    dw VENONAT
    dw DIGLETT
    dw MEOWTH
    dw PSYDUCK
    dw MANKEY
    dw GROWLITHE
    dw POLIWAG
    dw ABRA
    dw MACHOP
    dw BELLSPROUT
    dw TENTACOOL
    dw GEODUDE
    dw PONYTA
    dw SLOWPOKE
    dw FARFETCH_D
    dw DODUO
    dw SEEL
    dw GRIMER
    dw SHELLDER
    dw GASTLY
    dw ONIX
    dw DROWZEE
    dw KRABBY
    dw EXEGGCUTE
    dw CUBONE
    dw LICKITUNG
    dw KOFFING
    dw RHYHORN
    dw CHANSEY
    dw TANGELA
    dw KANGASKHAN
    dw HORSEA
    dw GOLDEEN
    dw MR_MIME
    dw SCYTHER
    dw PINSIR
    dw LAPRAS
    dw EEVEE
    dw OMANYTE
    dw KABUTO
    dw AERODACTYL
    dw SNORLAX
    dw DRATINI
    dw CHIKORITA
    dw CYNDAQUIL
    dw TOTODILE
    dw SENTRET
    dw HOOTHOOT
    dw LEDYBA
    dw SPINARAK
    dw CHINCHOU
    dw PICHU
    dw CLEFFA
    dw IGGLYBUFF
    dw TOGEPI
    dw NATU
    dw MAREEP
    dw MARILL
    dw SUDOWOODO
    dw HOPPIP
    dw AIPOM
    dw SUNKERN
    dw YANMA
    dw WOOPER
    dw MURKROW
    dw MISDREAVUS
    dw GIRAFARIG
    dw PINECO
    dw DUNSPARCE
    dw GLIGAR
    dw SNUBBULL
    dw QWILFISH
    dw SHUCKLE
    dw HERACROSS
    dw SNEASEL
    dw TEDDIURSA
    dw SLUGMA
    dw SWINUB
    dw CORSOLA
    dw REMORAID
    dw DELIBIRD
    dw MANTINE
    dw SKARMORY
    dw HOUNDOUR
    dw PHANPY
    dw STANTLER
    dw TYROGUE
    dw SMOOCHUM
    dw ELEKID
    dw MAGBY
    dw MILTANK
    dw LARVITAR
    dw TREECKO
    dw TORCHIC
    dw MUDKIP
    dw POOCHYENA
    dw ZIGZAGOON
    dw LOTAD
    dw SEEDOT
    dw NINCADA
    dw TAILLOW
    dw SHROOMISH
    dw SPINDA
    dw WINGULL
    dw SURSKIT
    dw WAILMER
    dw SKITTY
    dw KECLEON
    dw NOSEPASS
    dw TORKOAL
    dw SABLEYE
    dw BARBOACH
    dw LUVDISC
    dw CORPHISH
    dw FEEBAS
    dw CARVANHA
    dw TRAPINCH
    dw MAKUHITA
    dw ELECTRIKE
    dw NUMEL
    dw SPHEAL
    dw CACNEA
    dw SNORUNT
    dw AZURILL
    dw SPOINK
    dw PLUSLE
    dw MINUN
    dw MAWILE
    dw MEDITITE
    dw SWABLU
    dw DUSKULL
    dw ROSELIA
    dw SLAKOTH
    dw GULPIN
    dw TROPIUS
    dw WHISMUR
    dw CLAMPERL
    dw ABSOL
    dw SHUPPET
    dw SEVIPER
    dw ZANGOOSE
    dw RELICANTH
    dw ARON
    dw CASTFORM
    dw VOLBEAT
    dw ILLUMISE
    dw LILEEP
    dw ANORITH
    dw RALTS
    dw BAGON
    dw CHIMECHO
    ENDM